DATABASE = '''
CREATE DATABASE IF NOT EXISTS WORLD_OF_WUMPUS;'''

USE_DATABASE= '''
USE WORLD_OF_WUMPUS;'''

TABLE_MUNDO = '''
CREATE TABLE IF NOT EXISTS MUNDO (
  ID INTEGER PRIMARY KEY,
  SIZE INTEGER NOT NULL
);'''

TABLE_SALA = '''
CREATE TABLE IF NOT EXISTS SALA (
    MUNDO_ID INTEGER,
    POS_I INTEGER,
    POS_J INTEGER,
    PERCEPCAO VARCHAR(20),
    OBJETO VARCHAR(20),
    
    PRIMARY KEY(MUNDO_ID, POS_I, POS_J),
    FOREIGN KEY (MUNDO_ID) REFERENCES MUNDO(ID)
);'''

TABLE_AGENTE = '''
CREATE TABLE IF NOT EXISTS AGENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PONTOS INTEGER DEFAULT 0,
    FLECHAS INTEGER DEFAULT 0,
    REGISTRO DATETIME NOT NULL,
    TIPO INTEGER NOT NULL,
    FINAL VARCHAR(10),
    HISTORICO_PASSOS TEXT,
    QTD_PASSOS INTEGER DEFAULT 0,
    MUNDO_ID INTEGER NOT NULL,

    FOREIGN KEY(MUNDO_ID) REFERENCES MUNDO(ID)
);'''