DATABASE = '''
CREATE DATABASE IF NOT EXISTS WORLD_OF_WUMPUS;'''

USE_DATABASE= '''
USE WORLD_OF_WUMPUS;'''

TABLE_MUNDO = '''
CREATE TABLE IF NOT EXISTS MUNDO(
	ID INTEGER AUTO_INCREMENT,
	TAMANHO INTEGER,
	REGISTRO DATETIME UNIQUE,

	PRIMARY KEY(ID)
);'''

TABLE_AGENTE = '''
CREATE TABLE IF NOT EXISTS AGENTE (
	ID INTEGER AUTO_INCREMENT,
	TIPO FLOAT,
  	REGISTRO DATETIME UNIQUE,
    
  	PRIMARY KEY(ID)
);'''

TABLE_MEMORIA = '''
CREATE TABLE IF NOT EXISTS MEMORIA (
	ID INTEGER AUTO_INCREMENT,
	MUNDO_ID DATETIME,
  	REGISTRO DATETIME  UNIQUE,
	
	PRIMARY KEY(ID),
  	FOREIGN KEY(MUNDO_ID)
		REFERENCES MUNDO(REGISTRO)
    	ON DELETE CASCADE
    	ON UPDATE CASCADE
);'''

TABLE_SALA = '''
CREATE TABLE IF NOT EXISTS SALA (
	MUNDO_ID DATETIME,
	POS_X INTEGER,
	POS_Y INTEGER,
	POS_Z INTEGER DEFAULT 0,
	PERCEPCAO VARCHAR(20),
	OBJETO VARCHAR(20),
  
	PRIMARY KEY (MUNDO_ID, POS_X, POS_Y, POS_Z),
	FOREIGN KEY(MUNDO_ID) 
		REFERENCES MUNDO(REGISTRO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);'''

TABLE_CELULA = '''
CREATE TABLE IF NOT EXISTS CELULA (
	MEMORIA_ID DATETIME,
	POS_X INTEGER,
	POS_Y INTEGER,
	POS_Z INTEGER DEFAULT 0,
	CONTEUDO VARCHAR(20),
  
	PRIMARY KEY(MEMORIA_ID, POS_X, POS_Y, POS_Z),
	FOREIGN KEY (MEMORIA_ID)
		REFERENCES MEMORIA(REGISTRO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);'''

TABLE_EXECUCAO = '''
CREATE TABLE IF NOT EXISTS EXECUCAO (
	REGISTRO DATETIME,
	MUNDO_ID DATETIME,
	AGENTE_ID DATETIME,
	MEMORIA_ID DATETIME,
	RESULTADO VARCHAR(20),
    HISTORICO_DE_ACOES TEXT,
	FLECHAS_USADAS INTEGER DEFAULT 0,
	PONTOS INTEGER DEFAULT 0,
	QTD_PASSOS INTEGER DEFAULT 0,
	QTD_OUROS_COLETADOS INTEGER DEFAULT 0,
	QTD_WUMPUS_VENCIDOS INTEGER DEFAULT 0,
  
	PRIMARY KEY(REGISTRO),
	FOREIGN KEY(MUNDO_ID)
		REFERENCES MUNDO(REGISTRO)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(AGENTE_ID)
		REFERENCES AGENTE(REGISTRO)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(MEMORIA_ID)
		REFERENCES MEMORIA(REGISTRO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);'''
